### ISSUE TITLE
Loading of LSTM network does not work

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/mcfly#126]
Serializing and loading the JSON file of a LSTM network fails, because of the lambda layer. See for example this json file: [modelsmy_bestmodel_architecture.txt](https://github.com/NLeSC/mcfly/files/828251/modelsmy_bestmodel_architecture.txt). It has funny unicode characters in the lambda layer, and the following piece of code gives an error:

```python
import json
from keras.models import model_from_json

with open('modelsmy_bestmodel_architecture.json', 'r') as outfile:
        json_string_loaded = json.load(outfile)
model_repro = model_from_json(json_string_loaded)
```
See also [this issue in the Keras github](https://github.com/fchollet/keras/issues/2582)

**Comment by dafnevk** [comment]
This issue seems fixed with the newest version of Keras

**Comment by cWren0110** [comment]
I am running keras 2.0.3, with a Tensorflow-gpu 1.1.0 backend on Windows 10 with Python 3.5.3 and am still seeing this issue. I can save the weights without issue, but if I use `model.to_json()` or `model.save()` I get:

> File "yad2k.py", line 255, in _main
> json_string = model.to_json()
> File "D:\Users...\Anaconda3\lib\site-packages\keras\engine\topology.py", line 2546, in to_json
> model_config = self._updated_config()
> File "D:\Users...\Anaconda3\lib\site-packages\keras\engine\topology.py", line 2513, in _updated_config
> config = self.get_config()
> File "D:\Users...\Anaconda3\lib\site-packages\keras\engine\topology.py", line 2250, in get_config
> layer_config = layer.get_config()
> File "D:\Users...\Anaconda3\lib\site-packages\keras\layers\core.py", line 668, in get_config
> function = func_dump(self.function)
> File "D:\Users...\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 173, in func_dump
> code = marshal.dumps(func.code).decode('raw_unicode_escape')
> UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 195-196: truncated \uXXXX

Please let me know if I can include any more to help with the issue.

**Comment by vincentvanhees** [comment]
Hi, please clarify how this relates to issue #126
If there is no relation, then please post this as a new issue
